// -----------------------------------------------------------------------------
// This file is part of vAmiga
//
// Copyright (C) Dirk W. Hoffmann. www.dirkwhoffmann.de
// Licensed under the Mozilla Public License v2
//
// See https://mozilla.org/MPL/2.0 for license information
// -----------------------------------------------------------------------------

#pragma once

#include "JoystickTypes.h"

namespace vamiga {

static std::vector<GamePadTraits> gamePads = {
    {
        .name      = "Generic",
        .vendorID  = 0,
        .productID = 0,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "2 In 1 Joystick",
        .vendorID  = 3727,
        .productID = 3,
        .version   = 265,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo Adapter",
        .vendorID  = 11720,
        .productID = 12544,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo Adapter 2",
        .vendorID  = 11720,
        .productID = 12549,
        .version   = 512,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo Dogbone",
        .vendorID  = 11720,
        .productID = 20745,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo FC30 Pro",
        .vendorID  = 11720,
        .productID = 36864,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo FC30 Pro",
        .vendorID  = 11720,
        .productID = 14352,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo GameCube",
        .vendorID  = 11720,
        .productID = 10346,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B3,
    },{
        .name      = "8BitDo Lite 2",
        .vendorID  = 11720,
        .productID = 20754,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo Lite 2",
        .vendorID  = 11720,
        .productID = 20754,
        .version   = 512,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo Lite SE",
        .vendorID  = 11720,
        .productID = 20753,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo Lite SE",
        .vendorID  = 11720,
        .productID = 20753,
        .version   = 512,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo M30",
        .vendorID  = 3235,
        .productID = 36,
        .version   = 518,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo M30",
        .vendorID  = 11720,
        .productID = 20737,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo M30",
        .vendorID  = 11720,
        .productID = 20486,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo M30",
        .vendorID  = 11720,
        .productID = 1617,
        .version   = 256,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo Micro",
        .vendorID  = 11720,
        .productID = 36896,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo N30",
        .vendorID  = 11720,
        .productID = 20740,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo N30 Pro 2",
        .vendorID  = 11720,
        .productID = 36885,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo N30 Pro 2",
        .vendorID  = 11720,
        .productID = 10341,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo N64",
        .vendorID  = 11720,
        .productID = 10345,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo NEOGEO",
        .vendorID  = 11720,
        .productID = 36901,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo NEOGEO",
        .vendorID  = 11720,
        .productID = 36901,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo NEOGEO",
        .vendorID  = 11720,
        .productID = 36902,
        .version   = 256,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo NES30",
        .vendorID  = 4661,
        .productID = 43794,
        .version   = 1,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo NES30",
        .vendorID  = 11720,
        .productID = 43794,
        .version   = 1,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo NES30",
        .vendorID  = 11720,
        .productID = 10272,
        .version   = 256,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo NES30 Pro",
        .vendorID  = 8194,
        .productID = 36864,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo NES30 Pro",
        .vendorID  = 14368,
        .productID = 9,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo NES30 Pro",
        .vendorID  = 11720,
        .productID = 36865,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo P30",
        .vendorID  = 11720,
        .productID = 20743,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo P30",
        .vendorID  = 11720,
        .productID = 20744,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo Pro 2",
        .vendorID  = 11720,
        .productID = 24582,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo Pro 2",
        .vendorID  = 11720,
        .productID = 24582,
        .version   = 512,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo Receiver",
        .vendorID  = 11720,
        .productID = 12545,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo Receiver",
        .vendorID  = 11720,
        .productID = 12546,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo Receiver",
        .vendorID  = 11720,
        .productID = 12547,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo Receiver",
        .vendorID  = 11720,
        .productID = 12548,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo S30",
        .vendorID  = 11720,
        .productID = 26408,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8Bitdo SFC30 Gamepad",
        .vendorID  = 11720,
        .productID = 10288,
        .version   = 256,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo SFC30 Joystick",
        .vendorID  = 10256,
        .productID = 9,
        .version   = 0,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo SN30",
        .vendorID  = 11720,
        .productID = 20739,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo SN30",
        .vendorID  = 11720,
        .productID = 36882,
        .version   = 1,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo SN30",
        .vendorID  = 11720,
        .productID = 10304,
        .version   = 256,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo SN30 Pro",
        .vendorID  = 11720,
        .productID = 24577,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo SN30 Pro",
        .vendorID  = 11720,
        .productID = 24833,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo SN30 Pro Plus",
        .vendorID  = 11720,
        .productID = 24578,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo SN30 Pro Plus",
        .vendorID  = 11720,
        .productID = 24834,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo Ultimate",
        .vendorID  = 11720,
        .productID = 12306,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo Ultimate 2C",
        .vendorID  = 11720,
        .productID = 12315,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo Ultimate 2C",
        .vendorID  = 11720,
        .productID = 12317,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo Ultimate C",
        .vendorID  = 11720,
        .productID = 12309,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo Ultimate C",
        .vendorID  = 11720,
        .productID = 12310,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo Ultimate C",
        .vendorID  = 11720,
        .productID = 12311,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo Ultimate Wired",
        .vendorID  = 11720,
        .productID = 12305,
        .version   = 512,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo Ultimate Wireless",
        .vendorID  = 11720,
        .productID = 12307,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo Ultimate Wireless Controller",
        .vendorID  = 11720,
        .productID = 12307,
        .version   = 512,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo Zero",
        .vendorID  = 1440,
        .productID = 12850,
        .version   = 264,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo Zero",
        .vendorID  = 1440,
        .productID = 12850,
        .version   = 265,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "8BitDo Zero 2",
        .vendorID  = 11720,
        .productID = 36888,
        .version   = 1,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "8BitDo Zero 2",
        .vendorID  = 11720,
        .productID = 12848,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A31,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "Amazon Luna Controller",
        .vendorID  = 6473,
        .productID = 1049,
        .version   = 257,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Amazon Luna Controller",
        .vendorID  = 369,
        .productID = 1049,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Anbernic Gamepad",
        .vendorID  = 4104,
        .productID = 485,
        .version   = 1049,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Anbernic RG P01",
        .vendorID  = 13623,
        .productID = 4166,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Astro City Mini",
        .vendorID  = 3235,
        .productID = 39,
        .version   = 771,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "Astro City Mini",
        .vendorID  = 3235,
        .productID = 40,
        .version   = 771,
        .leftx      = HID_A3,
        .lefty      = HID_A4,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "ASUS Gamepad",
        .vendorID  = 2821,
        .productID = 17664,
        .version   = 49,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "ASUS ROG Kunai 3",
        .vendorID  = 2821,
        .productID = 30981,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "ASUS ROG Kunai 3",
        .vendorID  = 2821,
        .productID = 30982,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Atari VCS Classic",
        .vendorID  = 12880,
        .productID = 4097,
        .version   = 325,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Atari VCS Classic Controller",
        .vendorID  = 12880,
        .productID = 4097,
        .version   = 327,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Atari VCS Modern Controller",
        .vendorID  = 12880,
        .productID = 4098,
        .version   = 327,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Backbone One",
        .vendorID  = 13706,
        .productID = 513,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1_REV,
        .righty     = HID_A3_REV,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Backbone One",
        .vendorID  = 13706,
        .productID = 258,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Backbone One",
        .vendorID  = 13706,
        .productID = 514,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1_REV,
        .righty     = HID_A3_REV,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Backbone One",
        .vendorID  = 13706,
        .productID = 516,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Backbone One PlayStation Edition",
        .vendorID  = 13706,
        .productID = 515,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1_REV,
        .righty     = HID_A3_REV,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "BDA MOGA XP5-X Plus",
        .vendorID  = 9414,
        .productID = 35098,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "BDA MOGA XP5-X Plus",
        .vendorID  = 9414,
        .productID = 35099,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "BDA PS4 Fightpad",
        .vendorID  = 8406,
        .productID = 31018,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Brook Mars PS4 Controller",
        .vendorID  = 3090,
        .productID = 3616,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Brook Mars PS4 Controller",
        .vendorID  = 3090,
        .productID = 3617,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Cideko AK08b",
        .vendorID  = 1411,
        .productID = 45105,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Cthulhu",
        .vendorID  = 5336,
        .productID = 53198,
        .version   = 0,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Cyber Gadget GameCube Controller",
        .vendorID  = 2342,
        .productID = 34952,
        .version   = 648,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3_REV,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Cyborg V3 Rumble Pad PlayStation Controller",
        .vendorID  = 1699,
        .productID = 63010,
        .version   = 769,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Dual Box Wii Classic Adapter",
        .vendorID  = 7545,
        .productID = 769,
        .version   = 265,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "Elecom JC-W01U",
        .vendorID  = 1390,
        .productID = 8199,
        .version   = 528,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B2,
        .button2    = HID_B3,
    },{
        .name      = "Faceoff Deluxe Nintendo Switch Controller",
        .vendorID  = 3695,
        .productID = 388,
        .version   = 259,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Flydigi Vader 2",
        .vendorID  = 6421,
        .productID = 64,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B14,
        .button2    = HID_B15,
    },{
        .name      = "Flydigi Vader 2",
        .vendorID  = 1204,
        .productID = 9233,
        .version   = 1025,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Flydigi Vader 2",
        .vendorID  = 1204,
        .productID = 9234,
        .version   = 771,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "GameCube Controller Adapter",
        .vendorID  = 121,
        .productID = 6214,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A20,
        .lefty      = HID_A4,
        .righty     = HID_A8,
        .button1    = HID_B4,
        .button2    = HID_B0,
    },{
        .name      = "GameSir-T3 2.02",
        .vendorID  = 1452,
        .productID = 1562,
        .version   = 514,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Gamestop BB070 X360 Controller",
        .vendorID  = 7085,
        .productID = 63745,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "GameStop Gamepad",
        .vendorID  = 21319,
        .productID = 28001,
        .version   = 25697,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "GameStop PS4 Fun Controller",
        .vendorID  = 4544,
        .productID = 16385,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "GameStop Xbox 360 Controller",
        .vendorID  = 3695,
        .productID = 513,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "GameWare PC Control Pad",
        .vendorID  = 4607,
        .productID = 13105,
        .version   = 263,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "Google Stadia Controller",
        .vendorID  = 6353,
        .productID = 37888,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Gravis Eliminator Pro",
        .vendorID  = 1149,
        .productID = 16389,
        .version   = 257,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Gravis GamePad Pro",
        .vendorID  = 1064,
        .productID = 16385,
        .version   = 512,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "GreenAsia Joystick",
        .vendorID  = 3727,
        .productID = 3,
        .version   = 263,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A2,
        .button1    = HID_B2,
        .button2    = HID_B3,
    },{
        .name      = "Hori Fighting Commander 3 Pro",
        .vendorID  = 3853,
        .productID = 45,
        .version   = 4096,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Hori Fighting Commander 4 PS3",
        .vendorID  = 3853,
        .productID = 95,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Hori Fighting Commander 4 PS3",
        .vendorID  = 3853,
        .productID = 95,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Hori Fighting Commander 4 PS4",
        .vendorID  = 3853,
        .productID = 94,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Hori Fighting Commander 4 PS4",
        .vendorID  = 3853,
        .productID = 94,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Hori Fighting Commander PS3",
        .vendorID  = 3853,
        .productID = 132,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Hori Fighting Commander PS3",
        .vendorID  = 3853,
        .productID = 133,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Hori Fighting Stick Mini",
        .vendorID  = 6708,
        .productID = 515,
        .version   = 276,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Hori Fighting Stick mini 4 PS3",
        .vendorID  = 3853,
        .productID = 136,
        .version   = 256,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Hori Fighting Stick mini 4 PS4",
        .vendorID  = 3853,
        .productID = 135,
        .version   = 256,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Hori Gem Pad 3",
        .vendorID  = 3853,
        .productID = 77,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Hori PC Engine Mini Controller",
        .vendorID  = 3853,
        .productID = 312,
        .version   = 264,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Hori Pokken Tournament DX Pro",
        .vendorID  = 3853,
        .productID = 146,
        .version   = 256,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Hori Real Arcade Pro for Nintendo Switch",
        .vendorID  = 3853,
        .productID = 170,
        .version   = 1394,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "Hori Split Pad Fit",
        .vendorID  = 3853,
        .productID = 512,
        .version   = 279,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Hori Switch Split Pad Pro",
        .vendorID  = 3853,
        .productID = 512,
        .version   = 277,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Horipad 4 PS3",
        .vendorID  = 3853,
        .productID = 110,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Horipad 4 PS4",
        .vendorID  = 3853,
        .productID = 102,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Horipad FPS Plus 4",
        .vendorID  = 3853,
        .productID = 102,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Horipad Mini 4",
        .vendorID  = 3853,
        .productID = 238,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Horipad Nintendo Switch Controller",
        .vendorID  = 3853,
        .productID = 193,
        .version   = 1394,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Hyperkin N64 Adapter",
        .vendorID  = 11812,
        .productID = 3071,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Hyperkin N64 Controller Adapter",
        .vendorID  = 121,
        .productID = 38222,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A5,
        .lefty      = HID_A1,
        .righty     = HID_A2,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "iBuffalo Super Famicom Controller",
        .vendorID  = 1411,
        .productID = 8288,
        .version   = 0,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "InterAct AxisPad",
        .vendorID  = 1519,
        .productID = 3,
        .version   = 512,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A2,
        .button1    = HID_B2,
        .button2    = HID_B3,
    },{
        .name      = "Interact GoPad",
        .vendorID  = 1533,
        .productID = 12288,
        .version   = 272,
        .leftx      = HID_A0,
        .lefty      = HID_A1,
        .button1    = HID_B3,
        .button2    = HID_B4,
    },{
        .name      = "Joy-Con (L)",
        .vendorID  = 1406,
        .productID = 8198,
        .version   = 1,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Joy-Con (R)",
        .vendorID  = 1406,
        .productID = 8199,
        .version   = 1,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "JYS Adapter",
        .vendorID  = 12068,
        .productID = 45,
        .version   = 263,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "Logitech Controller",
        .vendorID  = 1133,
        .productID = 49689,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Logitech Dual Action",
        .vendorID  = 1133,
        .productID = 49686,
        .version   = 512,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Logitech Dual Action",
        .vendorID  = 1133,
        .productID = 49686,
        .version   = 768,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Logitech Dual Action",
        .vendorID  = 1133,
        .productID = 49686,
        .version   = 1044,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Logitech F310",
        .vendorID  = 1133,
        .productID = 49686,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Logitech F510",
        .vendorID  = 1133,
        .productID = 49688,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Logitech F710",
        .vendorID  = 1133,
        .productID = 49689,
        .version   = 773,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Logitech F710",
        .vendorID  = 1133,
        .productID = 49695,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Logitech RumblePad 2",
        .vendorID  = 1133,
        .productID = 49688,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1_REV,
        .righty     = HID_A3_REV,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Mad Catz PS3 Fightpad Pro",
        .vendorID  = 1848,
        .productID = 12880,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Mad Catz PS3 Fightstick TE S Plus",
        .vendorID  = 1848,
        .productID = 13188,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Mad Catz PS4 Fightpad Pro",
        .vendorID  = 1848,
        .productID = 33360,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Mad Catz PS4 Fightstick TE S Plus",
        .vendorID  = 1848,
        .productID = 33668,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Marvo GT-004",
        .vendorID  = 121,
        .productID = 6,
        .version   = 263,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "Mayflash Controller Adapter",
        .vendorID  = 3727,
        .productID = 12307,
        .version   = 273,
        .leftx      = HID_A0,
        .rightx     = HID_A6_REV,
        .lefty      = HID_A2,
        .righty     = HID_A4,
        .button1    = HID_B2,
        .button2    = HID_B4,
    },{
        .name      = "Mayflash GameCube Adapter",
        .vendorID  = 121,
        .productID = 6211,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A20,
        .lefty      = HID_A4,
        .righty     = HID_A8,
        .button1    = HID_B4,
        .button2    = HID_B0,
    },{
        .name      = "Mayflash GameCube Controller",
        .vendorID  = 121,
        .productID = 6212,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A5,
        .lefty      = HID_A1,
        .righty     = HID_A2,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Mayflash Magic NS",
        .vendorID  = 12068,
        .productID = 115,
        .version   = 512,
        .rightx     = HID_A2,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B4,
    },{
        .name      = "Mayflash Magic NS",
        .vendorID  = 121,
        .productID = 6354,
        .version   = 294,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "Mayflash Magic NS",
        .vendorID  = 8406,
        .productID = 42768,
        .version   = 259,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Mayflash Saturn Adapter",
        .vendorID  = 3727,
        .productID = 12304,
        .version   = 273,
        .button1    = HID_B0,
        .button2    = HID_B2,
    },{
        .name      = "Mayflash Wii Classic Adapter",
        .vendorID  = 2341,
        .productID = 1000,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "Mayflash Wii DolphinBar",
        .vendorID  = 121,
        .productID = 6147,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A8,
        .lefty      = HID_A4,
        .righty     = HID_A12,
        .button1    = HID_B8,
        .button2    = HID_B12,
    },{
        .name      = "Mayflash Wii U Pro Adapter",
        .vendorID  = 121,
        .productID = 6144,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A8,
        .lefty      = HID_A4,
        .righty     = HID_A12,
        .button1    = HID_B4,
        .button2    = HID_B8,
    },{
        .name      = "Mayflash Wii U Pro Adapter",
        .vendorID  = 121,
        .productID = 6144,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A8,
        .lefty      = HID_A4,
        .righty     = HID_A12,
        .button1    = HID_B4,
        .button2    = HID_B8,
    },{
        .name      = "Microsoft Dual Strike",
        .vendorID  = 1118,
        .productID = 40,
        .version   = 258,
        .rightx     = HID_A0,
        .righty     = HID_A1_REV,
        .button1    = HID_B3,
        .button2    = HID_B2,
    },{
        .name      = "Microsoft SideWinder",
        .vendorID  = 1118,
        .productID = 3,
        .version   = 262,
        .leftx      = HID_A0,
        .lefty      = HID_A1,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Microsoft SideWinder",
        .vendorID  = 1118,
        .productID = 7,
        .version   = 262,
        .leftx      = HID_A0,
        .lefty      = HID_A1,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Microsoft SideWinder Plug and Play",
        .vendorID  = 1118,
        .productID = 39,
        .version   = 257,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Mobapad Chitu HD",
        .vendorID  = 9029,
        .productID = 57365,
        .version   = 1394,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Moga Pro 2",
        .vendorID  = 8406,
        .productID = 25201,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "MOGA XP5A Plus",
        .vendorID  = 9414,
        .productID = 35114,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "MOGA XP5A Plus",
        .vendorID  = 9414,
        .productID = 35115,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "NeoGeo mini PAD Controller",
        .vendorID  = 9571,
        .productID = 1397,
        .version   = 512,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "NES 2-port Adapter",
        .vendorID  = 4754,
        .productID = 17995,
        .version   = 515,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "NEXT SNES Controller",
        .vendorID  = 2064,
        .productID = 58625,
        .version   = 262,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "Nintendo Switch Pro Controller",
        .vendorID  = 1406,
        .productID = 8201,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Nintendo Switch Pro Controller",
        .vendorID  = 1406,
        .productID = 8201,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Nintendo Switch Pro Controller",
        .vendorID  = 1406,
        .productID = 8201,
        .version   = 528,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Nintendo Switch Pro Controller",
        .vendorID  = 1406,
        .productID = 8201,
        .version   = 2047,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "NSO N64 Controller",
        .vendorID  = 1406,
        .productID = 8217,
        .version   = 1,
        .leftx      = HID_A0,
        .lefty      = HID_A1,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "NSO SNES Controller",
        .vendorID  = 1406,
        .productID = 8215,
        .version   = 1,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "NVIDIA Controller",
        .vendorID  = 2389,
        .productID = 29204,
        .version   = 1317,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Nyko Airflo EX",
        .vendorID  = 4683,
        .productID = 19713,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A2,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "PB Tails Choc",
        .vendorID  = 121,
        .productID = 6172,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "PDP PS3 Versus Fighting",
        .vendorID  = 3695,
        .productID = 265,
        .version   = 258,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Piranha Xtreme PS3 Controller",
        .vendorID  = 3727,
        .productID = 3,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A2,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "PowerA Core Plus Gamecube Controller",
        .vendorID  = 8406,
        .productID = 42769,
        .version   = 512,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "PowerA Nintendo Switch Controller",
        .vendorID  = 8406,
        .productID = 42769,
        .version   = 1296,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "PowerA Pro Ex",
        .vendorID  = 8406,
        .productID = 51821,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "PS2 Adapter",
        .vendorID  = 2064,
        .productID = 3,
        .version   = 262,
        .leftx      = HID_A0,
        .rightx     = HID_A4,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "PS3 Controller",
        .vendorID  = 1356,
        .productID = 616,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B14,
        .button2    = HID_B13,
    },{
        .name      = "PS3 Controller",
        .vendorID  = 1356,
        .productID = 616,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B14,
        .button2    = HID_B13,
    },{
        .name      = "PS3 Controller",
        .vendorID  = 1356,
        .productID = 616,
        .version   = 1394,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B14,
        .button2    = HID_B13,
    },{
        .name      = "PS4 Controller",
        .vendorID  = 1356,
        .productID = 2976,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "PS4 Controller",
        .vendorID  = 1356,
        .productID = 1476,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "PS4 Controller",
        .vendorID  = 1356,
        .productID = 1476,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "PS4 Controller",
        .vendorID  = 1356,
        .productID = 2508,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "PS5 Access Controller",
        .vendorID  = 1356,
        .productID = 3679,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "PS5 Controller",
        .vendorID  = 1356,
        .productID = 3302,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "PS5 Controller",
        .vendorID  = 1356,
        .productID = 3570,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "PS5 Controller",
        .vendorID  = 1356,
        .productID = 3302,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "PS5 Controller",
        .vendorID  = 1356,
        .productID = 3570,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "PXN P30 Pro Mobile",
        .vendorID  = 1118,
        .productID = 736,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Qanba Dragon Arcade Joystick PS3",
        .vendorID  = 11298,
        .productID = 9474,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Qanba Drone Arcade Stick",
        .vendorID  = 11298,
        .productID = 8192,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Raphnet SNES Adapter",
        .vendorID  = 10395,
        .productID = 86,
        .version   = 544,
        .button1    = HID_B1,
        .button2    = HID_B4,
    },{
        .name      = "Raphnet Wii Classic Adapter",
        .vendorID  = 10395,
        .productID = 128,
        .version   = 546,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B1,
        .button2    = HID_B4,
    },{
        .name      = "Razer Onza TE",
        .vendorID  = 5769,
        .productID = 64768,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Razer Panthera PS3 Controller",
        .vendorID  = 5426,
        .productID = 1026,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Razer Panthera PS4",
        .vendorID  = 5426,
        .productID = 1025,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Razer Raiju",
        .vendorID  = 5426,
        .productID = 4096,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Razer Raiju Mobile",
        .vendorID  = 5426,
        .productID = 1797,
        .version   = 257,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Razer Raion PS4 Fightpad",
        .vendorID  = 5426,
        .productID = 4352,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Razer Serval",
        .vendorID  = 5426,
        .productID = 2304,
        .version   = 512,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Razer Serval",
        .vendorID  = 5426,
        .productID = 2304,
        .version   = 14870,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Razer Wildcat",
        .vendorID  = 5426,
        .productID = 2563,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Redgear",
        .vendorID  = 9571,
        .productID = 1408,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "Retro Bit Sega Genesis Controller Adapter",
        .vendorID  = 4754,
        .productID = 18245,
        .version   = 512,
        .button1    = HID_B0,
        .button2    = HID_B2,
    },{
        .name      = "Retro Controller",
        .vendorID  = 121,
        .productID = 17,
        .version   = 0,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Retro Controller",
        .vendorID  = 121,
        .productID = 17,
        .version   = 261,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Retro Controller",
        .vendorID  = 1411,
        .productID = 8288,
        .version   = 256,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Retrode Adapter",
        .vendorID  = 1027,
        .productID = 38849,
        .version   = 0,
        .button1    = HID_B0,
        .button2    = HID_B4,
    },{
        .name      = "Retrolink SNES Controller",
        .vendorID  = 121,
        .productID = 17,
        .version   = 262,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "RetroUSB N64 RetroPort",
        .vendorID  = 4660,
        .productID = 4,
        .version   = 0,
        .leftx      = HID_A0,
        .lefty      = HID_A1,
        .button1    = HID_B7,
        .button2    = HID_B6,
    },{
        .name      = "Revolution Pro Controller",
        .vendorID  = 5227,
        .productID = 3329,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Revolution Pro Controller 3",
        .vendorID  = 5227,
        .productID = 3347,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Rii RK707",
        .vendorID  = 1356,
        .productID = 616,
        .version   = 4098,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B14,
        .button2    = HID_B13,
    },{
        .name      = "Rock Candy Nintendo Switch Controller",
        .vendorID  = 3695,
        .productID = 391,
        .version   = 261,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Rock Candy PS3",
        .vendorID  = 9414,
        .productID = 64254,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Samsung EIGP20",
        .vendorID  = 1256,
        .productID = 40960,
        .version   = 283,
        .leftx      = HID_A1,
        .rightx     = HID_A4,
        .lefty      = HID_A3,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B3,
    },{
        .name      = "Sanwa PlayOnline Mobile",
        .vendorID  = 1907,
        .productID = 260,
        .version   = 256,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Sega Genesis Mini 3B Controller",
        .vendorID  = 3235,
        .productID = 37,
        .version   = 518,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "Sega Saturn",
        .vendorID  = 6017,
        .productID = 1406,
        .version   = 0,
        .leftx      = HID_A0,
        .lefty      = HID_A2,
        .button1    = HID_B2,
        .button2    = HID_B4,
    },{
        .name      = "Sega Saturn",
        .vendorID  = 1204,
        .productID = 266,
        .version   = 0,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "SFC30 Joystick",
        .vendorID  = 4661,
        .productID = 43809,
        .version   = 0,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "SNES RetroPort",
        .vendorID  = 61440,
        .productID = 241,
        .version   = 0,
        .button1    = HID_B2,
        .button2    = HID_B3,
    },{
        .name      = "Sony DualShock 4 Adapter",
        .vendorID  = 1356,
        .productID = 2976,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Sony DualShock 4 V2",
        .vendorID  = 1356,
        .productID = 2508,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Sony PlayStation Adapter",
        .vendorID  = 26214,
        .productID = 1639,
        .version   = 648,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "Sony PlayStation Classic Controller",
        .vendorID  = 1356,
        .productID = 3290,
        .version   = 256,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "Sony PlayStation Vita",
        .vendorID  = 1356,
        .productID = 4919,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Steam Virtual Gamepad",
        .vendorID  = 1118,
        .productID = 654,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "SteelSeries Nimbus",
        .vendorID  = 273,
        .productID = 5152,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1_REV,
        .righty     = HID_A3_REV,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "SteelSeries Nimbus",
        .vendorID  = 273,
        .productID = 5152,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1_REV,
        .righty     = HID_A3_REV,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "SteelSeries Nimbus",
        .vendorID  = 4152,
        .productID = 5152,
        .version   = 1,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1_REV,
        .righty     = HID_A3_REV,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "SteelSeries Nimbus Plus",
        .vendorID  = 18760,
        .productID = 25924,
        .version   = 25955,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1_REV,
        .righty     = HID_A3_REV,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "SteelSeries Nimbus Plus",
        .vendorID  = 26958,
        .productID = 29557,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1_REV,
        .righty     = HID_A3_REV,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "SteelSeries Stratus Duo",
        .vendorID  = 4152,
        .productID = 5168,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "SteelSeries Stratus Duo",
        .vendorID  = 4152,
        .productID = 5169,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "SteelSeries Stratus XL",
        .vendorID  = 273,
        .productID = 5143,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1_REV,
        .righty     = HID_A3_REV,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "SteelSeries Stratus XL",
        .vendorID  = 273,
        .productID = 5143,
        .version   = 288,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1_REV,
        .righty     = HID_A3_REV,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Switch Hori Pad",
        .vendorID  = 3853,
        .productID = 246,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "SZMY Power PC Gamepad",
        .vendorID  = 30021,
        .productID = 4386,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Taito Egret II Mini Control Panel",
        .vendorID  = 2788,
        .productID = 1795,
        .version   = 1,
        .leftx      = HID_A0,
        .lefty      = HID_A1,
        .button1    = HID_B4,
        .button2    = HID_B2,
    },{
        .name      = "Taito Egret II Mini Controller",
        .vendorID  = 2788,
        .productID = 1794,
        .version   = 1,
        .leftx      = HID_A0,
        .lefty      = HID_A1,
        .button1    = HID_B4,
        .button2    = HID_B2,
    },{
        .name      = "TGZ Controller",
        .vendorID  = 121,
        .productID = 6172,
        .version   = 4099,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "THEC64 Joystick",
        .vendorID  = 7257,
        .productID = 36,
        .version   = 33,
        .leftx      = HID_A0,
        .lefty      = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "THEGamepad",
        .vendorID  = 7257,
        .productID = 38,
        .version   = 33,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "Thrustmaster Dual Analog 3.2",
        .vendorID  = 1103,
        .productID = 45845,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B2,
    },{
        .name      = "Thrustmaster eSwap Pro Controller",
        .vendorID  = 1103,
        .productID = 53262,
        .version   = 512,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Thrustmaster Firestorm Dual Power",
        .vendorID  = 1103,
        .productID = 45824,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B2,
    },{
        .name      = "Tomee NES Controller Adapter",
        .vendorID  = 7511,
        .productID = 33,
        .version   = 33,
        .button1    = HID_B1,
        .button2    = HID_B0,
    },{
        .name      = "Tomee Retro Controller",
        .vendorID  = 4797,
        .productID = 53269,
        .version   = 256,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "Tomee SNES Controller",
        .vendorID  = 4797,
        .productID = 53269,
        .version   = 0,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "Tomee SNES Controller Adapter",
        .vendorID  = 7511,
        .productID = 32,
        .version   = 33,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Trust Gamepad",
        .vendorID  = 5215,
        .productID = 453,
        .version   = 512,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B2,
        .button2    = HID_B1,
    },{
        .name      = "Twin USB Joystick",
        .vendorID  = 2064,
        .productID = 1,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A6,
        .lefty      = HID_A2,
        .righty     = HID_A4,
        .button1    = HID_B4,
        .button2    = HID_B2,
    },{
        .name      = "Uberwith Controller",
        .vendorID  = 9571,
        .productID = 1318,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Uniplay U6",
        .vendorID  = 6421,
        .productID = 30806,
        .version   = 272,
        .leftx      = HID_A1,
        .rightx     = HID_A4,
        .lefty      = HID_A3,
        .righty     = HID_A5,
        .button1    = HID_B3,
        .button2    = HID_B6,
    },{
        .name      = "Victrix PS4 Pro Fightstick",
        .vendorID  = 3695,
        .productID = 515,
        .version   = 1061,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Victrix PS4 Pro Fightstick",
        .vendorID  = 3695,
        .productID = 519,
        .version   = 1539,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Wii Remote",
        .vendorID  = 26967,
        .productID = 29807,
        .version   = 12328,
        .leftx      = HID_A0,
        .lefty      = HID_A1,
        .button1    = HID_B4,
        .button2    = HID_B5,
    },{
        .name      = "Wii U Pro Controller",
        .vendorID  = 26967,
        .productID = 29807,
        .version   = 12584,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B16,
        .button2    = HID_B15,
    },{
        .name      = "Xbox 360 Controller",
        .vendorID  = 1118,
        .productID = 654,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox 360 Controller",
        .vendorID  = 3695,
        .productID = 1025,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox 360 Controller",
        .vendorID  = 9414,
        .productID = 23812,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox Adaptive Controller",
        .vendorID  = 1118,
        .productID = 2826,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox Elite Controller Series 2",
        .vendorID  = 1118,
        .productID = 2821,
        .version   = 2307,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox One Controller",
        .vendorID  = 1118,
        .productID = 2835,
        .version   = 1297,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox One Controller",
        .vendorID  = 1118,
        .productID = 2848,
        .version   = 1297,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox One Controller",
        .vendorID  = 1118,
        .productID = 2848,
        .version   = 1299,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox One Controller",
        .vendorID  = 1118,
        .productID = 2848,
        .version   = 1301,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox One Controller",
        .vendorID  = 1118,
        .productID = 721,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox One Controller",
        .vendorID  = 1118,
        .productID = 733,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox One Controller",
        .vendorID  = 1118,
        .productID = 736,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox One Controller",
        .vendorID  = 1118,
        .productID = 736,
        .version   = 2307,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox One Controller",
        .vendorID  = 1118,
        .productID = 739,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox One Controller",
        .vendorID  = 1118,
        .productID = 746,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox One Controller",
        .vendorID  = 1118,
        .productID = 765,
        .version   = 2307,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox One PowerA Controller",
        .vendorID  = 9414,
        .productID = 21562,
        .version   = 0,
        .leftx      = HID_A0,
        .rightx     = HID_A3,
        .lefty      = HID_A1,
        .righty     = HID_A4,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox Series Controller",
        .vendorID  = 1118,
        .productID = 2835,
        .version   = 1281,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox Series Controller",
        .vendorID  = 1118,
        .productID = 2835,
        .version   = 1285,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox Series Controller",
        .vendorID  = 1118,
        .productID = 2835,
        .version   = 1289,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox Series Controller",
        .vendorID  = 1118,
        .productID = 2835,
        .version   = 1299,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox Series Controller",
        .vendorID  = 1118,
        .productID = 2835,
        .version   = 1301,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox Wireless Controller",
        .vendorID  = 1118,
        .productID = 2835,
        .version   = 1287,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox Wireless Controller",
        .vendorID  = 1118,
        .productID = 2835,
        .version   = 1303,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox Wireless Controller",
        .vendorID  = 1118,
        .productID = 2835,
        .version   = 1314,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Xbox Wireless Controller",
        .vendorID  = 1118,
        .productID = 2850,
        .version   = 1303,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A3,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "XiaoMi Controller",
        .vendorID  = 10007,
        .productID = 12612,
        .version   = 297,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B0,
        .button2    = HID_B1,
    },{
        .name      = "Zeroplus P4",
        .vendorID  = 3090,
        .productID = 3600,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    },{
        .name      = "Zeroplus P4",
        .vendorID  = 3090,
        .productID = 7696,
        .version   = 256,
        .leftx      = HID_A0,
        .rightx     = HID_A2,
        .lefty      = HID_A1,
        .righty     = HID_A5,
        .button1    = HID_B1,
        .button2    = HID_B2,
    }
};

}
